# Generated by Django 4.2.1 on 2023-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_pamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pAmount',
        ),
    ]
