# Generated by Django 4.2.1 on 2023-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_pamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
