# Generated by Django 4.2.1 on 2023-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_product_pamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pAmount1',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
