# Generated by Django 4.2.1 on 2023-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_product_pamount1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pAmount1',
        ),
        migrations.AddField(
            model_name='product',
            name='pAmount',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
