# Generated by Django 4.2.1 on 2023-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_remove_product_pamount1_product_pamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pAmount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
