# Generated by Django 4.2.1 on 2023-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_remove_product_pamount_product_pamount22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pAmount22',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
