# Generated by Django 4.2.1 on 2023-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_remove_product_pamount00_product_pamount11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pAmount11',
            field=models.IntegerField(),
        ),
    ]
