# Generated by Django 4.2.1 on 2023-05-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_alter_product_pamount11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pAmount11',
        ),
    ]
