# Generated by Django 4.2.1 on 2023-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_remove_product_pamount11'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pAmount11',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
