# Generated by Django 4.2.1 on 2023-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_remove_product_pamount11'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pAmount',
            field=models.CharField(default='10.0', max_length=10),
        ),
    ]
