# Generated by Django 4.2.1 on 2023-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_alter_product_description_alter_product_nameshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='nameShop',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='pName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopContact',
            field=models.CharField(max_length=20),
        ),
    ]
