# Generated by Django 4.2.1 on 2023-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_alter_product_description_alter_product_nameshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pAmount',
        ),
    ]
