# Generated by Django 4.2.1 on 2023-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_alter_product_pamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
