# Generated by Django 4.2.1 on 2023-05-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_remove_product_pamount_product_pamount1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pAmount1',
        ),
    ]
