# Generated by Django 4.2.1 on 2023-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_auto_20230531_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
